{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "convertigo.fullname" . }}-mysql-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.mysql.persistentVolume.size }}"
{{- if .Values.mysql.persistentVolume.storageClass }}
{{- if (eq "-" .Values.mysql.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.mysql.persistentVolume.storageClass }}"
{{- end }}
{{- end }}       
{{- end }}        