{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "convertigo.fullname" . }}-mysql
  labels:
    {{- include "convertigo.labels" . | nindent 4 }}-mysql
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 3306
  selector:
    {{- include "convertigo.selectorLabels" . | nindent 4 }}-mysql
{{- end }}       
